[semantic_release]
version_variable = "dmrid_lookup.py:__version__"  # Adjust this if your version variable is in a different file
branch = "main"  # The main branch for version releases
upload_to_pypi = true  # Enable PyPI upload
upload_to_release = true  # Enable GitHub release creation
build_command = "python -m build"  # Command to build the package
github_use_tag_release = true  # Use tags to create a release on GitHub
changelog_file = "CHANGELOG.md"  # Location of changelog file
major_on_zero = true  # Create a major release for 0.x versioning

# Correct configuration: branches should be a dictionary, not a list
branches = { "main": "main", "next": "next", "master": "master" }

