name: Build and Publish to PyPI 🚀

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0.0, v1.0.1, etc.)

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows writing to the repository

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history to get all tags

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade build twine

    - name: Build the package
      run: |
        python -m build  # Build the package

    - name: List dist folder for debugging
      run: |
        ls -la dist/  # Debugging step to verify dist files are generated

    - name: Upload to PyPI
      run: |
        python3 -m twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}  # Upload the package to PyPI

