name: Release Python Package 🚀

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for tags

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade python-semantic-release build twine

    - name: Run python-semantic-release
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEBUG: semantic_release*
      run: |
        set -x
        python3 -m semantic_release publish 

