name: Release Python Package 🚀

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history fetch
        ref: main  # Explicitly ensure it checks out the right branch

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install --upgrade build twine python-semantic-release

    - name: Check python-semantic-release version
      run: |
        python3 -m semantic_release --version  # Ensure latest version installed

    - name: Run python-semantic-release
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEBUG: semantic_release*
      run: |
        set -x
        python3 -m semantic_release publish

